# Generated by Django 6.0.1 on 2026-01-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_status',
            field=models.CharField(choices=[('register', 'Register'), ('verify_code', 'Verify Code'), ('edit_password', 'Edit password'), ('done', 'Done')], default='register'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile'),
        ),
    ]
